implemented comment section on article
olivershh/nc-news-network-frontend pull request #7
Opened 2022-09-27 14:18 UTC by olivershh

2022-09-27 14:28 UTC, xmenbteam approved these changes
This is coming along really well! Well done :)

2022-09-27 15:19 UTC, olivershh commented
Kind of a mess here as I clearly rushed and I think didnt confirm the previous merge? Just trying to wrap my head around it.

2022-09-27 15:32 UTC, olivershh commented
Accidentily broke it but fixed again with the above push

2022-09-28 08:12 UTC, xmenbteam requested changes
Because your comments are paginated in the back end, they're coming back in the wrong order so you're not seeing the most recent ones. Have a go at changing either the default order in the backend or changing the order they're queried from your front end?

2022-09-28 08:12 UTC, xmenbteam commented on src/components/CommentList.jsx
> +    })
`.catch` please!

2022-09-28 08:12 UTC, xmenbteam commented on src/components/PostComment.jsx
> +        postCommentByID(article_id, userComment)
This needs a `.then` and a `.catch` after it please!

2022-09-28 08:12 UTC, xmenbteam commented on src/components/api-calls.js
> +  const postObject = { usernme: "grumpy19", body: comment };
You spelled username wrong. You'd see this if you had a `.catch` in your component!

2022-09-28 09:01 UTC, olivershh commented on src/components/CommentList.jsx
> +    })
Sorted! Not dealing with the error yet, but think that will be covered in a later ticket

2022-09-28 09:01 UTC, olivershh commented on src/components/PostComment.jsx
> +        postCommentByID(article_id, userComment)
Sorted

2022-09-28 09:02 UTC, olivershh commented on src/components/api-calls.js
> +  const postObject = { usernme: "grumpy19", body: comment };
Sorted thanks.

2022-09-28 09:03 UTC, olivershh commented
Sorted backend to display by created_at descending
Also added a temp comment_id to new comments (used Date.now() since thats the key Im giving react.

2022-09-28 09:16 UTC, merged